# Generated by Django 3.2.11 on 2022-08-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
